orders/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('pizza_all/', views.pizza_all, name='all_pizzas'),
    path('pizza_meat/', views.pizza_meat, name='meat_pizzas'),
    path('pizza_veg/', views.pizza_veg, name='veg_pizzas'),
    path('pizza_grill/', views.pizza_grill, name='grill_pizzas'),
    path('pizza_hot/', views.pizza_hot, name='hot_pizzas'),
    path('pizza_closed/', views.pizza_closed, name='closed_pizzas'),

    re_path(r'^add-to-cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name="add_to_cart"),
    path('cart/', views.order_details, name='order_details'),


]

pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('orders.urls', 'orders'), namespace='orders')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.BBLoginView.as_view(), name='login'),
    path('logout/', views.BBLogoutView.as_view(), name='logout'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'orders/css/app.css' %}" />
    <script src="https://unpkg.com/htmx.org@1.9.6"></script>
  </head>
  <body>
    <div class="wrapper">
      <div class="header">
        <div class="container">
          <div class="header__logo">
            <img width="38" src="{% static 'orders/img/pizza-logo.svg' %}" alt="Pizza logo" />
            <div>
              <h1>Django Pizza</h1>
              <p>самая вкусная пицца во вселенной</p>
            </div>
          </div>

          {% if user.is_authenticated %}
          <div class="header__profile">
              <a href="{% url 'users:profile' %}" class="button button--cart">
              <span>Профиль</span>
              </a>
          </div>
          {% endif %}

          <div class="header__login">
             {% if user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="button button--cart">
              <span>Выход</span>
            </a>
            {% else %}
            <a href="{% url 'users:login' %}" class="button button--cart">
              <span>Авторизация</span>
            </a>
            {% endif %}
          </div>

          <div class="header__cart">
            <a href="{% url 'orders:order_details' %}" class="button button--cart">
              <span>От 1200 ₸</span>
              <div class="button__delimiter"></div>
              <svg
                width="18"
                height="18"
                viewBox="0 0 18 18"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M6.33333 16.3333C7.06971 16.3333 7.66667 15.7364 7.66667 15C7.66667 14.2636 7.06971 13.6667 6.33333 13.6667C5.59695 13.6667 5 14.2636 5 15C5 15.7364 5.59695 16.3333 6.33333 16.3333Z"
                  stroke="white"
                  stroke-width="1.8"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
                <path
                  d="M14.3333 16.3333C15.0697 16.3333 15.6667 15.7364 15.6667 15C15.6667 14.2636 15.0697 13.6667 14.3333 13.6667C13.597 13.6667 13 14.2636 13 15C13 15.7364 13.597 16.3333 14.3333 16.3333Z"
                  stroke="white"
                  stroke-width="1.8"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
                <path
                  d="M4.78002 4.99999H16.3334L15.2134 10.5933C15.1524 10.9003 14.9854 11.176 14.7417 11.3722C14.4979 11.5684 14.1929 11.6727 13.88 11.6667H6.83335C6.50781 11.6694 6.1925 11.553 5.94689 11.3393C5.70128 11.1256 5.54233 10.8295 5.50002 10.5067L4.48669 2.82666C4.44466 2.50615 4.28764 2.21182 4.04482 1.99844C3.80201 1.78505 3.48994 1.66715 3.16669 1.66666H1.66669"
                  stroke="white"
                  stroke-width="1.8"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <span>3</span>
            </a>
          </div>
        </div>
      </div>
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>