orders/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('pizza_all/', views.pizza_all, name='all_pizzas'),
    path('pizza_meat/', views.pizza_meat, name='meat_pizzas'),
    path('pizza_veg/', views.pizza_veg, name='veg_pizzas'),
    path('pizza_grill/', views.pizza_grill, name='grill_pizzas'),
    path('pizza_hot/', views.pizza_hot, name='hot_pizzas'),
    path('pizza_closed/', views.pizza_closed, name='closed_pizzas'),

    re_path(r'^add-to-cart/(?P<item_id>[-\w]+)/$', views.add_to_cart, name="add_to_cart"),
    path('cart/', views.order_details, name='order_details'),


]

pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('orders.urls', 'orders'), namespace='orders')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from users.models import Users


class Category(models.Model):
    name = models.CharField(max_length=50)

    @staticmethod
    def get_all_categories():
        return Category.objects.all()

    def __str__(self):
        return self.name


class Pizzas(models.Model):
    date_created = models.DateTimeField(default=timezone.now, editable=False)
    date_updated = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100, verbose_name="Название пиццы")
    price = models.IntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    pizza_image = models.ImageField(null=True, blank=True, upload_to="orders/images/")
    class Meta:
        ordering = ['date_updated']
        # indexes = [models.Index(fields=['fieldname1', 'fieldname1']), ]

    def __str__(self):
        return self.title


class OrderItem(models.Model):
    pizza = models.OneToOneField(Pizzas, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    date_added = models.DateTimeField(auto_now=True)
    date_ordered = models.DateTimeField(null=True)
    quantity = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.quantity = self.quantity + 1
        super().save(*args, **kwargs)  # Call the "real" save() method.

    def __str__(self):
        return self.product.name


class Order(models.Model):
    ref_code = models.CharField(max_length=15)
    owner = models.ForeignKey(Users, on_delete=models.SET_NULL, null=True)
    is_ordered = models.BooleanField(default=False)
    items = models.ManyToManyField(OrderItem)
    date_ordered = models.DateTimeField(auto_now=True)

    def get_cart_items(self):
        return self.items.all()

    def get_cart_total(self):
        return sum([item.pizza.price for item in self.items.all()])

    def __str__(self):
        return '{0} - {1}'.format(self.owner, self.ref_code)

orders/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
from django.urls import reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.http import QueryDict
from .models import Pizzas, OrderItem, Order
from users.models import Users

from .extras import generate_order_id


def index(request):
    queryset = Pizzas.objects.all().order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/index.html', {'pizzas': queryset, 'page_obj': page_obj})

def pizza_all(request):

    queryset = Pizzas.objects.all().order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/components/pizza_component.html', {'pizzas': queryset, 'page_obj': page_obj})

def pizza_meat(request):

    queryset = Pizzas.objects.all().filter(category=1).order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/components/pizza_component.html', {'pizzas': queryset, 'page_obj': page_obj})

def pizza_veg(request):

    queryset = Pizzas.objects.all().filter(category=2).order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/components/pizza_component.html', {'pizzas': queryset, 'page_obj': page_obj})


def pizza_grill(request):

    queryset = Pizzas.objects.all().filter(category=3).order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/components/pizza_component.html', {'pizzas': queryset, 'page_obj': page_obj})


def pizza_hot(request):

    queryset = Pizzas.objects.all().filter(category=4).order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/components/pizza_component.html', {'pizzas': queryset, 'page_obj': page_obj})


def pizza_closed(request):

    queryset = Pizzas.objects.all().filter(category=5).order_by('-date_updated')
    paginator = Paginator(queryset, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'orders/components/pizza_component.html', {'pizzas': queryset, 'page_obj': page_obj})

@login_required
def add_to_cart(request, **kwargs):
    # cringe?
    auth_user_id = request.session.get('_auth_user_id')
    user = get_object_or_404(Users, pk=auth_user_id) #user=request.user doesnt work

    pizza = Pizzas.objects.filter(id=kwargs.get('item_id',"")).first()
    # create orderItem of the selected product
    order_pizza, status = OrderItem.objects.get_or_create(pizza=pizza)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user, is_ordered=False)
    user_order.items.add(order_pizza)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()
    order_pizza.save()
    return redirect(reverse('orders:index'))

@login_required
def get_user_pending_order(request):
    # get order for the correct user
    auth_user_id = request.session.get('_auth_user_id')
    user = get_object_or_404(Users, pk=auth_user_id)  # user=request.user doesnt work
    order = Order.objects.filter(owner=user, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order

    }

    return render(request, 'orders/cart.html', context)

templates/orders/cart-empty.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Document</title>
    <link rel="stylesheet" href="../../src/css/app.css" />
  </head>
  <body>
    <div class="wrapper">
      <div class="header">
        <div class="container">
          <div class="header__logo">
            <img width="38" src="../../src/img/pizza-logo.svg" alt="Pizza logo" />
            <div>
              <h1>React Pizza</h1>
              <p>самая вкусная пицца во вселенной</p>
            </div>
          </div>
          <div class="header__cart">
            <div class="button button--cart">
              <span>520 ₽</span>
              <div class="button__delimiter"></div>
              <svg
                width="18"
                height="18"
                viewBox="0 0 18 18"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M6.33333 16.3333C7.06971 16.3333 7.66667 15.7364 7.66667 15C7.66667 14.2636 7.06971 13.6667 6.33333 13.6667C5.59695 13.6667 5 14.2636 5 15C5 15.7364 5.59695 16.3333 6.33333 16.3333Z"
                  stroke="white"
                  stroke-width="1.8"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
                <path
                  d="M14.3333 16.3333C15.0697 16.3333 15.6667 15.7364 15.6667 15C15.6667 14.2636 15.0697 13.6667 14.3333 13.6667C13.597 13.6667 13 14.2636 13 15C13 15.7364 13.597 16.3333 14.3333 16.3333Z"
                  stroke="white"
                  stroke-width="1.8"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
                <path
                  d="M4.78002 4.99999H16.3334L15.2134 10.5933C15.1524 10.9003 14.9854 11.176 14.7417 11.3722C14.4979 11.5684 14.1929 11.6727 13.88 11.6667H6.83335C6.50781 11.6694 6.1925 11.553 5.94689 11.3393C5.70128 11.1256 5.54233 10.8295 5.50002 10.5067L4.48669 2.82666C4.44466 2.50615 4.28764 2.21182 4.04482 1.99844C3.80201 1.78505 3.48994 1.66715 3.16669 1.66666H1.66669"
                  stroke="white"
                  stroke-width="1.8"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                />
              </svg>
              <span>3</span>
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="container container--cart">
          <div class="cart cart--empty">
            <h2>Корзина пустая <icon>😕</icon></h2>
            <p>
              Вероятней всего, вы не заказывали ещё пиццу.<br />
              Для того, чтобы заказать пиццу, перейди на главную страницу.
            </p>
            <img src="/img/empty-cart.png" alt="Empty cart" />
            <a href="/" class="button button--black">
              <span>Вернуться назад</span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/orders/cart.html
<!DOCTYPE html>
{% extends "../base.html" %}

{% block content %}
      <div class="content">
        <div class="container container--cart">
          <div class="cart">
            <div class="cart__top">
              <h2 class="content__title"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M6.33333 16.3333C7.06971 16.3333 7.66667 15.7364 7.66667 15C7.66667 14.2636 7.06971 13.6667 6.33333 13.6667C5.59695 13.6667 5 14.2636 5 15C5 15.7364 5.59695 16.3333 6.33333 16.3333Z" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M14.3333 16.3333C15.0697 16.3333 15.6667 15.7364 15.6667 15C15.6667 14.2636 15.0697 13.6667 14.3333 13.6667C13.597 13.6667 13 14.2636 13 15C13 15.7364 13.597 16.3333 14.3333 16.3333Z" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M4.78002 4.99999H16.3334L15.2134 10.5933C15.1524 10.9003 14.9854 11.176 14.7417 11.3722C14.4979 11.5684 14.1929 11.6727 13.88 11.6667H6.83335C6.50781 11.6694 6.1925 11.553 5.94689 11.3393C5.70128 11.1256 5.54233 10.8295 5.50002 10.5067L4.48669 2.82666C4.44466 2.50615 4.28764 2.21182 4.04482 1.99844C3.80201 1.78505 3.48994 1.66715 3.16669 1.66666H1.66669" stroke="white" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
 Корзина</h2>
              <div class="cart__clear">
                <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M2.5 5H4.16667H17.5" stroke="#B6B6B6" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M6.66663 5.00001V3.33334C6.66663 2.89131 6.84222 2.46739 7.15478 2.15483C7.46734 1.84227 7.89127 1.66667 8.33329 1.66667H11.6666C12.1087 1.66667 12.5326 1.84227 12.8451 2.15483C13.1577 2.46739 13.3333 2.89131 13.3333 3.33334V5.00001M15.8333 5.00001V16.6667C15.8333 17.1087 15.6577 17.5326 15.3451 17.8452C15.0326 18.1577 14.6087 18.3333 14.1666 18.3333H5.83329C5.39127 18.3333 4.96734 18.1577 4.65478 17.8452C4.34222 17.5326 4.16663 17.1087 4.16663 16.6667V5.00001H15.8333Z" stroke="#B6B6B6" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M8.33337 9.16667V14.1667" stroke="#B6B6B6" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
<path d="M11.6666 9.16667V14.1667" stroke="#B6B6B6" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

                <span>Очистить корзину</span>
              </div>
            </div>
            <div class="content__items">

                {% for item in order.get_cart_items %}
              <div class="cart__item">
  <div class="cart__item-img">
    <img
      class="pizza-block__image"
       {% if not item.pizza.pizza_image.url %}
                src="https://dodopizza-a.akamaihd.net/static/Img/Products/Pizza/ru-RU/b750f576-4a83-48e6-a283-5a8efb68c35d.jpg"
                {% else %}
                src="../media/{{item.pizza.pizza_image}}"
                {% endif %}
      alt="Pizza"
    />
  </div>
  <div class="cart__item-info">
    <h3>{{ item.pizza.title }}</h3>
<!--    <p>тонкое тесто, 26 см.</p>-->
  </div>
  <div class="cart__item-count">
    <div class="button button--outline button--circle cart__item-count-minus">
      <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.92001 3.84V5.76V8.64C5.92001 9.17016 5.49017 9.6 4.96001 9.6C4.42985 9.6 4.00001 9.17016 4.00001 8.64L4 5.76L4.00001 3.84V0.96C4.00001 0.42984 4.42985 0 4.96001 0C5.49017 0 5.92001 0.42984 5.92001 0.96V3.84Z" fill="#EB5A1E"/>
<path d="M5.75998 5.92001L3.83998 5.92001L0.959977 5.92001C0.429817 5.92001 -2.29533e-05 5.49017 -2.29301e-05 4.96001C-2.2907e-05 4.42985 0.429817 4.00001 0.959977 4.00001L3.83998 4L5.75998 4.00001L8.63998 4.00001C9.17014 4.00001 9.59998 4.42985 9.59998 4.96001C9.59998 5.49017 9.17014 5.92001 8.63998 5.92001L5.75998 5.92001Z" fill="#EB5A1E"/>
</svg>

    </div>
    <b>2</b>
    <div class="button button--outline button--circle cart__item-count-plus">
      <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.92001 3.84V5.76V8.64C5.92001 9.17016 5.49017 9.6 4.96001 9.6C4.42985 9.6 4.00001 9.17016 4.00001 8.64L4 5.76L4.00001 3.84V0.96C4.00001 0.42984 4.42985 0 4.96001 0C5.49017 0 5.92001 0.42984 5.92001 0.96V3.84Z" fill="#EB5A1E"/>
<path d="M5.75998 5.92001L3.83998 5.92001L0.959977 5.92001C0.429817 5.92001 -2.29533e-05 5.49017 -2.29301e-05 4.96001C-2.2907e-05 4.42985 0.429817 4.00001 0.959977 4.00001L3.83998 4L5.75998 4.00001L8.63998 4.00001C9.17014 4.00001 9.59998 4.42985 9.59998 4.96001C9.59998 5.49017 9.17014 5.92001 8.63998 5.92001L5.75998 5.92001Z" fill="#EB5A1E"/>
</svg>

    </div>
  </div>
  <div class="cart__item-price">
    <b>{{ item.pizza.price }}</b>
  </div>
  <div class="cart__item-remove">
    <div class="button button--outline button--circle">
      <svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M5.92001 3.84V5.76V8.64C5.92001 9.17016 5.49017 9.6 4.96001 9.6C4.42985 9.6 4.00001 9.17016 4.00001 8.64L4 5.76L4.00001 3.84V0.96C4.00001 0.42984 4.42985 0 4.96001 0C5.49017 0 5.92001 0.42984 5.92001 0.96V3.84Z" fill="#EB5A1E"/>
<path d="M5.75998 5.92001L3.83998 5.92001L0.959977 5.92001C0.429817 5.92001 -2.29533e-05 5.49017 -2.29301e-05 4.96001C-2.2907e-05 4.42985 0.429817 4.00001 0.959977 4.00001L3.83998 4L5.75998 4.00001L8.63998 4.00001C9.17014 4.00001 9.59998 4.42985 9.59998 4.96001C9.59998 5.49017 9.17014 5.92001 8.63998 5.92001L5.75998 5.92001Z" fill="#EB5A1E"/>
</svg>

    </div>
  </div>
</div>

              {% endfor %}

            </div>
            <div class="cart__bottom">
              <div class="cart__bottom-details">
                <span> Всего пицц: <b>{{ order.get_cart_items.count }}</b> </span>
                   {% if order.get_cart_total != None %}
                <span> Сумма заказа: <b>{{ order.get_cart_total }}</b> </span>
                  {% endif %}
              </div>
              <div class="cart__bottom-buttons">
                <a href="/" class="button button--outline button--add go-back-btn">
                  <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M7 13L1 6.93015L6.86175 1" stroke="#D3D3D3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
</svg>

                  <span>Вернуться назад</span>
                </a>
                <div class="button pay-btn">
                  <span>Оплатить сейчас</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>


<section>
   <div class="row">
    <table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>no.</th>
        <th>Item</th>
        <th>Price</th>
      </tr>
      {% for item in order.get_cart_items %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            {{ item.product.name }}
            <span class="pull-right">
              <a href="" data-balloon="remove this item from cart" class="text-danger" onclick="return confirm_delete();">
                <i class="fas fa-trash"></i>
              </a>
            </span>
          </td>
          <td>{{ item.pizza.price }}</td>
        </tr>
      {% empty %}
        <tr>
          <td colspan= 3> You have not added any items yet.</td>
        </tr>
      {% endfor %}
      <tr>
        {% if order.get_cart_total != None %}
        <td colspan=2>
          <strong class="pull-right">Order Total:</strong>
        </td>

        <td colspan= 1>
          $<strong>{{ order.get_cart_total }}</strong>
        </td>
        {% endif %}
      </tr>
      <tr>
        <td colspan=1 >
          <a href="" class="btn btn-warning pull-left">
            {% if order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a>
        </td>
        <td colspan=2>
          {% if order.get_cart_items %}
            <a href="" class="pull-right btn btn-primary">Proceed To Checkout</a>
          {% endif %}
        </td>
      </tr>
    </table>

   </div>
 </section>

{% endblock %}

templates/orders/index.html
<!DOCTYPE html>
{% extends "../base.html" %}


{% block content %}
      <div class="content">
        <div class="container">
          <div class="content__top">
            <div class="categories">
              <ul>
                <li class="active" hx-get="{% url 'orders:all_pizzas' %}" hx-target="#body" hx-swap="outerHTML">Все</li>
                <li hx-get="{% url 'orders:meat_pizzas' %}" hx-target="#body" hx-swap="outerHTML">Мясные</li>
                <li hx-get="{% url 'orders:veg_pizzas' %}" hx-target="#body" hx-swap="outerHTML">Вегетарианская</li>
                <li hx-get="{% url 'orders:grill_pizzas' %}" hx-target="#body" hx-swap="outerHTML">Гриль</li>
                <li hx-get="{% url 'orders:hot_pizzas' %}" hx-target="#body" hx-swap="outerHTML">Острые</li>
                <li hx-get="{% url 'orders:closed_pizzas' %}" hx-target="#body" hx-swap="outerHTML">Закрытые</li>
              </ul>
            </div>
            <div class="sort">
              <div class="sort__label">
                <svg
                  width="10"
                  height="6"
                  viewBox="0 0 10 6"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M10 5C10 5.16927 9.93815 5.31576 9.81445 5.43945C9.69075 5.56315 9.54427 5.625 9.375 5.625H0.625C0.455729 5.625 0.309245 5.56315 0.185547 5.43945C0.061849 5.31576 0 5.16927 0 5C0 4.83073 0.061849 4.68424 0.185547 4.56055L4.56055 0.185547C4.68424 0.061849 4.83073 0 5 0C5.16927 0 5.31576 0.061849 5.43945 0.185547L9.81445 4.56055C9.93815 4.68424 10 4.83073 10 5Z"
                    fill="#2C2C2C"
                  />
                </svg>
                <b>Сортировка по:</b>
                <span>популярности</span>
              </div>
              <div class="sort__popup">
                <ul>
                  <li class="active">популярности</li>
                  <li>цене</li>
                  <li>алфавиту</li>
                </ul>
              </div>
            </div>
          </div>
          <h2 class="content__title">Все пиццы</h2>
          <div class="content__items" id="body">

            {% for pizza in pizzas %}
            <div class="pizza-block">
              <img
                class="pizza-block__image"
                {% if not pizza.pizza_image.url %}
                src="https://dodopizza-a.akamaihd.net/static/Img/Products/Pizza/ru-RU/b750f576-4a83-48e6-a283-5a8efb68c35d.jpg"
                {% else %}
                src="media/{{pizza.pizza_image}}"
                {% endif %}
                alt="Pizza"
              />
              <h4 class="pizza-block__title">{{ pizza.title }}</h4>
              <div class="pizza-block__bottom">
                <div class="pizza-block__price">{{ pizza.price }} ₸</div>
                <div class="button button--outline button--add" onclick="redirectToLink('{% url 'orders:add_to_cart' pizza.id %}')">
                  <a href="{% url 'orders:add_to_cart' pizza.id %}"></a>
                  <svg
                    width="12"
                    height="12"
                    viewBox="0 0 12 12"
                    fill="none"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      d="M10.8 4.8H7.2V1.2C7.2 0.5373 6.6627 0 6 0C5.3373 0 4.8 0.5373 4.8 1.2V4.8H1.2C0.5373 4.8 0 5.3373 0 6C0 6.6627 0.5373 7.2 1.2 7.2H4.8V10.8C4.8 11.4627 5.3373 12 6 12C6.6627 12 7.2 11.4627 7.2 10.8V7.2H10.8C11.4627 7.2 12 6.6627 12 6C12 5.3373 11.4627 4.8 10.8 4.8Z"
                      fill="white"
                    />
                  </svg>
                  <span>Добавить</span>
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </body>

<script>
  function redirectToLink(url) {
    window.location.href = url;
  }
</script>
</html>

{% endblock %}