pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('orders.urls', 'orders'), namespace='orders')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('login/', views.BBLoginView.as_view(), name='login'),
    path('logout/', views.BBLogoutView.as_view(), name='logout'),

]

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, AbstractUser
from django.utils.translation import gettext_lazy as _

class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
			email=self.normalize_email(email),
			username=username,
        )


        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


#  Users(AbstractBaseUser):
# inherited from AbstractUser because of is_staff requirement when trying to login in admin panel
class Users(AbstractUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default = False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = MyAccountManager()

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

users/forms.py
from django import forms
from .models import Users


from django.contrib.auth.forms import UserCreationForm


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Users
        fields = ('email', 'username', 'password1', 'password2',)

users/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import RegistrationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .models import Users
from django.shortcuts import get_object_or_404


@login_required
def profile(request):
    user_id = request.user.id
    queryset = Users.objects.get(id=user_id)  # get_object_or_404(Account, pk=user_id)
    return render(request, 'users/profile.html', {'profile': queryset})


def register(request):
    if request.method == 'GET':
        form = RegistrationForm()
        return render(request, 'users/register.html', {'form': form})

    elif request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            login(request, user)
            messages.success(request, ('успешная регистрация'))
            return HttpResponseRedirect('../../')
        else:
            return render(request, 'users/register.html', {'form': form})


class BBLoginView(LoginView):
    template_name = 'users/login.html'


class BBLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'users/logout.html'

templates/users/login.html
<!DOCTYPE html>
{% extends "../base.html" %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>


{% block title %}Вход{% endblock %}

    {% block content %}

{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed, please login with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

<form method="post" action="{% url 'users:login' %}">
{% csrf_token %}
<table>

<tr>
  <td>{{ form.username.label_tag }}</td>
  <td>{{ form.username }}</td>
</tr>

<tr>
  <td>{{ form.password.label_tag }}</td>
  <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>


<div class="cart__bottom-buttons">
    <a href="/" class="button button--add">
        <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M7 13L1 6.93015L6.86175 1" stroke="#D3D3D3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
        <span>Вернуться назад</span>
    </a>
</div>


    {% endblock %}
</body>
</html>

templates/users/logout.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% block title %}Выход{% endblock %}
{% block content %}
<h2 >Выход</h2>
Вы успешно вышли с сайта.

<div class="cart__bottom-buttons">
    <a href="/" class="button button--add">
        <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M7 13L1 6.93015L6.86175 1" stroke="#D3D3D3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
        <span>Вернуться назад</span>
    </a>
</div>
{% endblock %}


</body>
</html>

templates/users/profile.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

{% block content %}
<h2 class="content__title">Профиль</h2>
<div class="cart__item-info">
    <h3>Имя пользователя: {{ profile.username }}</h3>
    {% if profile.is_admin %} <h3>Является ли пользователь админом: Да </h3>
    {% else %}
    {% endif %}
</div>

<div class="cart__bottom-buttons">
    <a href="/" class="button button--add">
        <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M7 13L1 6.93015L6.86175 1" stroke="#D3D3D3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
        <span>Вернуться назад</span>
    </a>
</div>


{% endblock %}

</body>
</html>

templates/users/register.html
<!DOCTYPE html>
{% extends "../base.html" %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Account</title>
</head>
<body>
    {% block content %}
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}

        {{form.as_ul}}

        <input class="btn btn-primary" type="submit"/>
        <input type="hidden" name="next" value="{{ next }}" />

    </form>


<div class="cart__bottom-buttons">
    <a href="/" class="button button--add">
        <svg width="8" height="14" viewBox="0 0 8 14" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M7 13L1 6.93015L6.86175 1" stroke="#D3D3D3" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
        </svg>
        <span>Вернуться назад</span>
    </a>
</div>
    {% endblock %}
</body>
</html>